%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\samcl\OneDrive\Documents\Gyroscope\Boatroll\Data_5.txt
%
% Auto-generated by MATLAB on 27-Oct-2021 15:14:34

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time5", "Var2", "Var3", "roll5", "Var5"];
opts.SelectedVariableNames = ["time5", "roll5"];
opts.VariableTypes = ["double", "string", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\samcl\OneDrive\Documents\Gyroscope\Boatroll\Data_5.txt", opts);

%% Convert to output type
time5 = tbl.time5;
roll5 = tbl.roll5;

%% Clear temporary variables
clear opts tbl