%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\samcl\OneDrive\Documents\Gyroscope\Boatroll\Data_15.txt
%
% Auto-generated by MATLAB on 27-Oct-2021 15:08:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time15", "Var2", "Var3", "Roll15", "Var5"];
opts.SelectedVariableNames = ["time15", "Roll15"];
opts.VariableTypes = ["double", "string", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\samcl\OneDrive\Documents\Gyroscope\Boatroll\Data_15.txt", opts);

%% Convert to output type
time15 = tbl.time15;
roll15 = tbl.Roll15;

%% Clear temporary variables
clear opts tbl