%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\samcl\OneDrive\Documents\Gyroscope\Boatroll\Data_10.txt
%
% Auto-generated by MATLAB on 27-Oct-2021 15:13:08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time10", "Var2", "Var3", "roll10", "Var5"];
opts.SelectedVariableNames = ["Time10", "roll10"];
opts.VariableTypes = ["double", "string", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var5"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\samcl\OneDrive\Documents\Gyroscope\Boatroll\Data_10.txt", opts);

%% Convert to output type
time10 = tbl.Time10;
roll10 = tbl.roll10;

%% Clear temporary variables
clear opts tbl